FROM python:3.12-slim

WORKDIR /demo

COPY lib ./lib
COPY api ./api

RUN pip install --no-cache-dir ./lib
RUN pip install --no-cache-dir ./api

WORKDIR /demo/api

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
